name: Deployment
on: 
  push:
    tags: 
     - patch
     - minor
     - major
jobs:
  deploy:
    runs-on: macos-11
    env:
      GITHUB_ACTION: ${{ github.action_path }}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set release type environment
        run: |
          echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Install polyglot
        run: |
          make install
          export PATH="$GOPATH/bin:$PATH"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: maierj/fastlane-action@v2.2.1
        with:
          lane: 'deploy'
          verbose: 'true'
          options: '{ "type": "${{ env.RELEASE_TYPE }}" }'
