name: Deployment
on: 
  push:
    tags: 
     - patcht
     - minort
     - majort
jobs:
  deploy:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_TYPE
          echo ${{ env.RELEASE_TYPE }}
      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install polyglot
        run: |
          make install
